(defvar *arch-enemy* nil)
(defun pudding-eater (person) 
  (cond ((eq person 'Henry) 
         (setf *arch-enemy* 'stupid-lisp-alien)
         '(curse you lisp alien - you ate my pudding)
         )
        ((eq person 'Johnny) 
         (setf *arch-enemy* 'useless-old-johnny)
         '(I hope you choked on my pudding Johnny)
         )
        (t
         '(why you ate my pudding stranger?))
        )
  )

(defun pudding-eater-case (person)
  (case person
    ((henry) 
     (setf *arch-enemy* 'stupid-lisp-alien) 
     '(curse you lisp alien - you ate my pudding)
     )
    ((johnny)
     (setf *arch-enemy* 'useless-old-johnny)
     '(I hope you choked on my pudding Johnny)
     )
    (otherwise
     '(why you ate my pudding stranger?)
     )
    )
  )